spring:
  application:
    name: demo1
  datasource:
    url: jdbc:mysql://mysql-b-1-service:3306/mydb1
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
app:
  origin: host