spring:
  application:
    name: demo1
  datasource:
    url: jdbc:mysql://mysql-b-1-service:3306/mydb1
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
app:
  origin: host

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: app
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"
